name = "zerithdb-signaling"
main = "src/platforms/cloudflare.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [{ name = "SIGNALING_ROOM", class_name = "SignalingDurableObject" }]

[[migrations]]
tag = "v1"
new_classes = ["SignalingDurableObject"]
